language: python

env:
  global:
    # travis encrypt GIT_EMAIL=<commit email> GH_TOKEN=<personal access token>
    secure: muOdofd/oT849Qe5iFtEjn11vvOQUvYXCJ9gN+/K0TS9wUX9+QDk3qoTRKoyBKw8EAVfNT6wcfESRoRh8iug1YHUweKPlxUgoqzqTzT3ailxC2qX6n79lqaAyRK+AeclDZGH0ESze8wNZYZzKanicC3X84GVYJpst+DiEDue3MM=

branches:
  only:
  - source

git:
  submodules: false

sudo: false

install:
- set -e
- openssl aes-256-cbc -K $encrypted_9f32b8d262b8_key -iv $encrypted_9f32b8d262b8_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key && eval `ssh-agent -s` && ssh-add deploy-key
- git config --global user.name "Phil Elson"
- git config --global user.email $GIT_EMAIL

- export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
- wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH:$(pwd)"
- conda config --set show_channel_urls True
- conda install --yes --quiet -c conda-forge conda-execute conda=4.5.3

- noleaky git submodule update --quiet --init --recursive
- noleaky git clone --depth=50 --branch=master git@github.com:pelson/pelson.github.io.git output_branch

- echo "Built from the following commits:"
- git log --oneline -n 1 >> log_message.txt
- LOG_MESSAGE=$(cat log_message.txt)


script:
    
- conda execute -v make.py publish
- cd output_branch
- git add --all *
- git status
- git commit -am "${LOG_MESSAGE}"
#- noleaky git push origin master
- echo "PUSH IS DISABLED (because I was losing content)!"
